### ISSUE TITLE
Feature Request: Verify URL when Application Source Type is Git URL

### ISSUE THREAD

**Issue by mmartin24** [epinio/ui#107]
### Is your feature request related to a problem?

On  Epinio UI v0.7.1, attempting to create an app from this URL will end up with a 500 error: https://github.com/epinio/epinio/tree/main/assets/sample-app
Regardless of the motives, the user will have to wait until the error displays, reload the page, erase that app and start all over.
![image (1)](https://user-images.githubusercontent.com/37271841/168545039-ac3c2e73-1f81-4c8c-9db9-f45550c489cb.png)
![image (2)](https://user-images.githubusercontent.com/37271841/168545033-bd1d64cf-e5bc-435e-a370-e43a1b4b11a1.png)

### Solution you'd like

This could be prevented with an initial validation on the URL.

**Comment by richard-cox** [comment]
Blocked on https://github.com/rancher/dashboard/issues/4238 / https://github.com/rancher/dashboard/pull/4999

**Comment by richard-cox** [comment]
There should be an easy way to add url validation to form fields now. We probably just want to apply it to this individual field atm. Double check with @Sean-McQ before starting

**Comment by cnotv** [comment]
Further changes may be integrated also with https://github.com/rancher/dashboard/issues/6633

**Comment by thehejik** [comment]
Verified fixed in `ghcr.io/epinio/epinio-ui:v1.5.1-0.0.3`

It doesn't check if the repository exists or not but if the url doens't match to the used regexp it will not let you go further:
![image](https://user-images.githubusercontent.com/12828077/204851592-c0e8cc55-b61d-4214-98b4-040bc4d7c3a8.png)

regexp is `      const gitRegex = /(https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]+\.[^\s]{2,}|www\.[a-zA-Z0-9]+\.[^\s]{2,})/gm;
`

**Comment by richard-cox** [comment]
There's more detail in https://github.com/rancher/dashboard/pull/7049#pullrequestreview-1158195426, but basically we should only validate if the url is syntactically fine

**Comment by richard-cox** [comment]
Shipped in v1.5.1
