### ISSUE TITLE
Link to cli binaries from UI

### ISSUE THREAD

**Issue by agracey** [epinio/ui#144]
**Is your feature request related to a problem? Please describe.**
If a developer is just coming on board, it would be very helpful if an admin could give access to the UI then have a link there to pull the latest cli tooling. While it's definitely not hard to find with google, it's just one less potential source of frustration for a new user.

**Describe the solution you'd like**
On the UI, we should include a link somewhere to the right release for the targeted cluster

**Comment by mmartin24** [comment]
@scures can you pls confirm if this is the intended link?
If, so the link seems to work, but the cli downloads fail for me. Also the "See all packages". Is perhaps this intended to be fixed on another ticket?

![image](https://user-images.githubusercontent.com/37271841/184861462-2d88058f-56e8-47e7-b73e-a1b191d8d93a.png)
![image](https://user-images.githubusercontent.com/37271841/184861863-b36e20cd-7568-4748-b369-393eccc50541.png)

**Comment by richard-cox** [comment]
We should have added additional information to the issue. The URL is as Sorin said, made up using the version of epinio. When running locally this is set as an env var when running the backend (see https://github.com/epinio/ui/blob/dev/docs/developer/install-latest-standalone-ui.md#to-run-the-latest-version-of-the-ui `./jetstream` command. To test this you could set that to `v1.1.0` which should produce a valid link

**Comment by jimmykarily** [comment]
Let's make sure the linked version matches the epinio-server version currently deployed and not always the latest epinio binary version.

**Comment by richard-cox** [comment]
@jimmykarily It's the version we show bottom left of the UI, normally supplied via chart value, so should already align correctly on epinio release. On a slightly related note, I think we have a separate issue to update where that version comes from (api /info request rather than helm chart --> ui backend env var)

**Comment by mmartin24** [comment]
> We should have added additional information to the issue. The URL is as Sorin said, made up using the version of epinio. When running locally this is set as an env var when running the backend (see https://github.com/epinio/ui/blob/dev/docs/developer/install-latest-standalone-ui.md#to-run-the-latest-version-of-the-ui `./jetstream` command. To test this you could set that to `v1.1.0` which should produce a valid link

@richard-cox  I tried to check this and I am not sure it works as expected.
I followed your advice and set environment within `./jetstream` to `1.1.0` instead that to `dev`:
![image](https://user-images.githubusercontent.com/37271841/185098837-2bda3425-8fe8-4db3-b1fd-722bdc812c3b.png) 
![image](https://user-images.githubusercontent.com/37271841/185099113-bfa76333-3e1c-4297-a8f5-79a49dfe3571.png)

However I still get broken links.

When I look at the error, it seems not only a version issue but another part of the URL. For the Apple binary for instance, it points to this URL that does not work: `https://github.com/epinio/epinio/releases/download/1.1.0/epinio-darwin-arm64` instead of  `https://github.com/epinio/epinio/releases/tag/v1.1.0/epinio-darwin-arm64`. So it seems the `/download/` part should be replaced by `/tag/` and the version should be preceeded by a `v`. Is this something to be done here or will be automatically set once into Epinio?

**Comment by mmartin24** [comment]
Just realized of an error on the last comment.
It was suggested  by @richard-cox to create the environment with `v.1.1.0` and I just added `1.1.0`. ok, I will replace that, but I understand still the switch `download` for `tag` still applies. Checking it again.

**Comment by mmartin24** [comment]
Actually it works correctly when the environment is set right. @richard-cox all good here, pls disregard the previous comments. 
Pasting screenshot of this:
![image](https://user-images.githubusercontent.com/37271841/185102751-60747c5a-54e3-49f0-8e80-09e302e7e2bc.png)

**Comment by mmartin24** [comment]
Ok, closing issue. Checked in latest epinio dev and working. Added to our test plan.
