### ISSUE TITLE
[UI] Gitlab integration

### ISSUE THREAD

**Issue by scures** [epinio/ui#173]
Covers step forth https://github.com/epinio/ui/issues/63#issuecomment-1164180440

- Wire the Gitlab API
- Allow fetching repos (and details) from user/organization

**Comment by mmartin24** [comment]
Tested in latest `epinio-dev`

- Simple deployment from Gitlab
- Update source from different commit
- Trying to deploy Gitlab application from manifest
- Details page with different commits present

All of them seemed to work.

![image](https://user-images.githubusercontent.com/37271841/233042792-0c993064-c313-4be0-8406-b673e9de56bf.png)

Some observations are:

- 404 appears after setting username (known and non-critical)
- When creating a Gitlab app using a manifest, the UI seems not to select GitURL instead of Gitlab as source type (reported here: https://github.com/epinio/ui/issues/226)

**Comment by mmartin24** [comment]
Retested in `v1.8.0-rc1` and working

![image](https://user-images.githubusercontent.com/37271841/234810777-d62759ed-82d1-44ff-8681-af2b98bfd25a.png)
