### ISSUE TITLE
[ui] Improve GitPicker timeouts

### ISSUE THREAD

**Issue by richard-cox** [epinio/ui#221]
- add a `delay` field to anything that kicks off a http request
- make that delay configurable
- set this to something more that missing or 500ms

**Comment by mmartin24** [comment]
I see the 1000ms enforced [here](https://github.com/rancher/dashboard/pull/9155/files#diff-1123419a392b9d98c670d5e093c2f6628f315622e7a19b6a989dbec58740c00eR32) but I am not sure how to check it. I have typed a repo `epinio` when creating an app with source type `github` and looked in `browser dev tools > network > timing` for the generated `rpos?per_page=100` response, but that does not seem to be it:
![image (1)](https://github.com/epinio/ui/assets/37271841/be4314de-7cc7-40f5-b0b0-df01bd51e3f6)

Could someone pls let me know where to specifically look for it?

Thanks

**Comment by torchiaf** [comment]
### Summary
Fixes https://github.com/epinio/ui/issues/221


@mmartin24 putting some notes to clarify how it works.

We added a `1000ms` delay, which takes effect from the moment the user finishes typing a value into any field of Edit/Create source form, to the moment the https request is actually sent to the backend.
Just an example: Having a delay of 5000 ms, if you type a username you will have to wait 5 seconds before to see the https request in the browser console and get the list of repositories.

The delay is applied to the fields below:

- `Username/Organization` : typed value is the `key` of API request; it's sent with a delay of 1000 ms. It returns the list or repos for that `key` username or organization, if exists.
- `Repository`: typed value is the searching keyword, given a list of repositories; it's sent with a delay of 1000 ms but this delay is masked to the user, since the search is made also by the UI dropdown over the list of repositories already in its cache.
- `Branch`: same of Repository.

**Comment by mmartin24** [comment]
@torchiaf , the use case was clear: add 1000ms (or 1 s) and wait after the user is done typing the value to be searched. The issue I have a problem with is measuring it.

Looking at this screenshot, it seems it took 512.34ms (roughly half a second) to get the server response after the request was done:
![image](https://github.com/epinio/ui/assets/37271841/c2e712f4-354d-46e7-8705-ca7634c4239e)

So either is not waiting for 1 second or I am not looking at the right place to measure it. If this is the case, pls let me know where to measure it. You can also resolve this issue if you think it does not need a check on qa side.

**Comment by richard-cox** [comment]
1) User types
2) User stops typing
3) 1 second delay
4) http request associated with input field starts

I think there's some cases where we cache responses and there's no http request. 

In summary, no network request should be made within a second of the user stopping typing

**Comment by mmartin24** [comment]
Ok, so I have no easy way to measure this, but I was able to check the improvement by doing this:

- Go to Applications > Github > SourceType=Github
- Type any repo name (ie: `superdev`)
- Add a number every time you get a response and observe the time spent 
Observed behavior: the new version adds a delay (I cannot say if it is 1 second but it is a delay)

We can see this comparing the previous steps on these 2 videos, one without this fix and with one.

- Without delay added (request is observed earlier):

https://github.com/epinio/ui/assets/37271841/769b7e09-e314-444e-90fb-0c5fa5e5cd83

- With delay added (request is observed slower):

https://github.com/epinio/ui/assets/37271841/b7afc3d9-d2e0-4e10-b0cf-b9d50227ba74

I'd say the improvement is observed, so closing the issue
