### ISSUE TITLE
[UI] Update Application origin git provider strings to match new values

### ISSUE THREAD

**Issue by richard-cox** [epinio/ui#234]
See https://github.com/epinio/epinio/pull/2298 (specifically https://github.com/epinio/epinio/pull/2298/files#diff-1ce4bd480f02d0d89d05c5733bbdadacc601e586fe8593e4e70ea34e56a9b469R39)

We should do this once https://github.com/rancher/dashboard/pull/8797 has merged and we can update our instance

**Comment by mmartin24** [comment]
@torchiaf or @richard-cox , mind pls write a few lines on what is the expected behavior / how to test this one?

Pushing an app with the new ` --git-provider` flag as in [here](https://github.com/epinio/epinio/pull/2298#issuecomment-1549544001) and then checking everything is ok in UI?

If so, would I understand that at the moment only `git`, `github`, `gitlab` should work at the moment?

**Comment by richard-cox** [comment]
This one falls under the _test everything_ flag. 

It will affect creating applications, editing app source, download app manifest, supply manifest in create/edit app screens, etc.

This PR shouldn't affect the other source types (folder, archive), they should still work as normal.

**Comment by mmartin24** [comment]
ok, being that case not an issue.
Checked that uploads of apps with different source types (archive, folders, giturl, GitHub, and GitLab) as well as manifest, etc, and works. We noticed some sluggishness in the UI like when selecting combos from Gitlab but that does not seem related to this since the functionality is ok.
