### ISSUE TITLE
[ui] Embedded - Show charts based on Kube metric server resources

### ISSUE THREAD

**Issue by richard-cox** [epinio/ui#270]
Epinio view - show graphs if we have access to metrics server
- ~metrics.k8s.io.podmetrics~ this info is already shown via info from epinio api
- metrics.k8s.io.nodemetrics

**Comment by richard-cox** [comment]
need to consider if we can do the same for other epinio resources (service instances, configurations, etc)

**Comment by richard-cox** [comment]
QA team - This can either be tested now, or closed and added to https://github.com/epinio/ui/issues/265. Just let us know

**Comment by mmartin24** [comment]
> QA team - This can either be tested now, or closed and added to #265. Just let us know

@richard-cox I am not sure about the context of this issue.
Please close it and add it to https://github.com/epinio/ui/issues/265
Thanks.

**Comment by mmartin24** [comment]
@richard-cox , @torchiaf  I am closing this and adding it #265 to clear up our dashboard.
I am still unsure what the expectation is, so we need to clarify when #265 is to be checked.

I have seen the pr attached (https://github.com/epinio/ui/pull/290) but I am not sure about the expected behavior. Things such:

- If this is a feature solely for Rancher /  Rancher extension as currently I don't see it in the standalone version
- Are the sole values `CPU` and `memory`?
- Are they supposed to be the used amount of what is shown in the screenshot?
![image](https://github.com/epinio/ui/assets/37271841/3577dda8-8c73-4815-9afc-c140e12cf4f8)

**Comment by torchiaf** [comment]
@mmartin24 quick updates:

1.  Yes, the info banner will be visible only in extension mode.
2. Yes, the information are only about available `cpu` and `memory` in the Epinio node.
3. Resource's values between Epinio and Rancher should be consistent. Needs further investigations on how those values are  calculated both sides. I would say this is a bug ATM

**Comment by thehejik** [comment]
The values match if you compare the metrics on the node where epinio is running - but the link `Show Metrics in Cluster Explorer` is pointing to general `Cluster Dashboard` (maybe not so accurate or showing different values?) and not to a specific node.

![image](https://github.com/epinio/ui/assets/12828077/5bad1ebe-4c76-47bb-8fd5-48e21fa70dd6)
