### ISSUE TITLE
[UI] Allow namespace creation when deploying default chart in Rancher

### ISSUE THREAD

**Issue by mmartin24** [epinio/ui#319]
**Is your feature request related to a problem? Please describe.**
When deploying a default Epinio chart namespace creation is not possible; however, this is possible when deploying a custom Epinio chart. 

Installation options when using default Epinio charts:
![image](https://github.com/epinio/ui/assets/37271841/ec87cad6-8c83-453f-b274-3f4f06a6e78c)

Installation options when using custom Epinio chart from repo:
![image](https://github.com/epinio/ui/assets/37271841/25f844b0-6aab-46ff-8d2f-0ab4887110da)

Besides the inconsistency, this may be an issue while working with the new Epinio extension. We noticed that attempting to deploy the default Epinio chart without selecting the Epinio namespace (because it cannot be added) will end up with the application not being found in the cluster:
![image](https://github.com/epinio/ui/assets/37271841/1c05f09a-0cdf-4b56-a943-88a7ca829bef)

**Describe the solution you'd like**
Creating a namespace from the default chart should be possible

**Describe alternatives you've considered**

**Additional context**

**Comment by thehejik** [comment]
it looks like the extension is expecting Epinio to be installed in `epinio` namespace. Epinio rancher app is using hardcoded namespace `cattle-epinio-system`.

**Comment by richard-cox** [comment]
There's two parts to this

1) Namespace is not shown when installing 102.0.3+up1.8.1 (rancher release), but is for 1.9.0 (dev epinio release)
This is because the 1.8.1 chart contains the annotation `catalog.cattle.io/release-name`, which tells the UI / Rancher that the chart must be installed to it's a specific namespace. Going on @enrichman comment this requirement has been dropped. So the newer chart must not contain the annotation. This is working as expected.

2) When installing epinio to a namespace other than `epinio` it's not recognised as an epinio cluster by the extension
We hadn't tracked this in an issue, so created https://github.com/epinio/ui/issues/322

**Comment by richard-cox** [comment]
Given the above, i think we can close this one
