### ISSUE TITLE
Dashboard Crash after a logout/login

### ISSUE THREAD

**Issue by torchiaf** [epinio/ui#361]
**Setup**
- Epinio version: latest
- Epinio UI version: latest

**To Reproduce**

- Run Epinio in Embedded mode `API=https://rancher yarn dev`
- Login to Rancher dashboard
- Go to Epinio -> select an Epinio instance -> go to Epinio dashboard
- click Logout
- Login to Rancher dashboard
- Go to Epinio

**Result**
Got an error:
![image](https://github.com/epinio/ui/assets/26394656/496fe9d1-a039-4a94-84e7-07bfae6938e4)

**Comment by thehejik** [comment]
This seems to be fixed in extension `epinio-1.11.0-2`, `rancher:v2.8.0-rc3` and post `epinio:v1.11.0-rc1` from main + latest ui. 

I tried to perform login/logout for both auth methods - local auth and dex, all good.
[embedded-logout2-2023-11-20_14.18.40.webm](https://github.com/epinio/ui/assets/12828077/78041b22-eff8-4236-a817-462789edb1ad)

Can be closed.
