### ISSUE TITLE
Dashboard crash on app creation if no namespace is defined

### ISSUE THREAD

**Issue by kkaempf** [epinio/ui#52]
#### Steps to reproduce

- delete all (epinio) namespaces
- try to create an app

#### Result

`this.options[0] is undefined `

JS console shows

> TypeError: this.options[0] is undefined
>     data InputWithSelect.vue:84
>     VueJS 74
>     _callee$ NuxtJS
>     Babel 12
>     NuxtJS 2
>     VueJS 22
> at client.js:97:14

**Comment by richard-cox** [comment]
@catherineluse I've stumbled on a related dashboard ticket that would be helpful for this https://github.com/rancher/dashboard/issues/2513 (see my comment there as well)

**Comment by juadk** [comment]
Dashboard doesn't crash anymore, you can define a name for your application but that's not possible to click on next without selecting a namespace.

**Comment by catherineluse** [comment]
Richard and I reproduced the error too. It only happens when all the namespaces are deleted (including workspace) so there are none to select.

Our approach would be to make it so that the namespace select drop-down would become a select-or-create menu instead. So you would be required to create a namespace, but you would have the opportunity to do it without leaving the form.

Richard said the namespace select menu should already have that functionality- I just have to enable it.

**Comment by juadk** [comment]
Makes sense with a select-or-create menu.

**Comment by richard-cox** [comment]
I've fixed this in `epinio-dev` temporarily by adding a warning in the create namespace and create config pages. In the future we'll tie in the work from https://github.com/rancher/dashboard/issues/2513 such that a ns can be created inline

**Comment by richard-cox** [comment]
User can no create their namespaces in all places where they can select a namespace
