### ISSUE TITLE
Unable to unbind a service from an application

### ISSUE THREAD

**Issue by juadk** [epinio/ui#53]
When I was writing down the UI test plan, I realized we missed a test.
We didn't try to unbind a service from an application and that seems to not working as expected.

Steps to reproduce:

1. Go to Epinio dashboard
2. Go to app section
3. Click on the 3 dots menu of your application and choose "Edit Config"
4. Click on the Services tab, remove the service and click on Save

![image](https://user-images.githubusercontent.com/6025636/142885068-d0ecf451-6c82-4604-a699-63e24e5b03f3.png)

After saving, the service is still bind to the application.

![image](https://user-images.githubusercontent.com/6025636/142885595-ee46e3e3-3ee2-45fe-90f5-38e1d897a009.png)

### Env:
Rancher image: rancher/rancher:v2.6.2
Rancher dashboard branch: epinio-v0.2.0
Epinio: 0.2.0
Rancher under docker connected to an external GKE cluster

**Comment by richard-cox** [comment]
On investigating... this is a timing issue. The application PATCH request sends the correct information and gets the OK response. Immediately after this we make a GET request for the same application (to fetch the latest version of the resource) and it contains the old list of bound services. So on page refresh the correct application without the service is shown.

@jimmykarily I'm not sure what's happening under the hood, but is the sync PATCH request returning in a way that the following GET returns stale data?

**Comment by thardeck** [comment]
@juadk does the described function actually remove the service or just unbinds it?
Because from my perspective the logical step would be to undbind it in the app menu, but at the same time you mention remove and we do not have `PATCH` implemented for bind/unbind, just `POST` and `DELETE` which work fine in my tests and do not have the issue described here.
We only have `PATCH` for manipulating services in general.

@richard-cox where can I access the code of the ui and look out implementation details.

**Comment by juadk** [comment]
If I remember correctly, when I click on the cross, it unbinds the service from the app only. I think I said "remove" with the meaning of removing the service from service tab of the application I'm double checking.

**Comment by juadk** [comment]
I can still reproduce the issue. When I click on the cross next to my service name in the app menu:
![image](https://user-images.githubusercontent.com/6025636/150745516-369c9c66-4b95-4e11-822e-9ad2698ce3ce.png)
Then, I save:
![image](https://user-images.githubusercontent.com/6025636/150745779-93bb8434-f760-439f-b567-9d0d45c4a4d2.png)
After saving, I can still see the service attached to the app:
![image](https://user-images.githubusercontent.com/6025636/150746004-6170122c-4187-4884-88c3-57b75d6c99df.png)

**Comment by richard-cox** [comment]
@thardeck Sorry, still catching up, the specific code for http request is https://github.com/rancher/dashboard/blob/epinio-dev/products/epinio/models/applications.js#L293 , there we supply the new bound services during the application PATCH

**Comment by thardeck** [comment]
At the moment we only support  manipulating service bindings on the app level. The separate api endpoint is called `servicebindings` which provides `POST` and `DELETE`:

https://github.com/epinio/epinio/blob/c9d36acc9f451c04b2e192e5e6e4c09cd8875755/docs/references/api/swagger.json#L627

https://github.com/epinio/epinio/blob/c9d36acc9f451c04b2e192e5e6e4c09cd8875755/docs/references/api/swagger.json#L662

I can run a curl `DELETE` against the `.../applications/[application_name]/servicesbindings/[service_name]` endpoint of an application and then `GET` against `.../services/[service_name]` in direct succession and it shows correctly that there is no service bound to this app.

While `GET` for the service api endpoint does list the apps bound to this service, neither `PATCH` nor `PUT` on this service api endpoint allow to manipulate app bindings.

@richard-cox Would this be an option for you to use the specific endpoint?



Patching a service does allow all kinds of data without returning an error though (e.g. `'{ "whatever": true }'`), so it is easy to miss that the call had no effect.

**Comment by jimmykarily** [comment]
@thardeck can we also fix the comment here? https://github.com/epinio/epinio/blob/main/internal/api/v1/service/update.go#L15-L16 (must have been a copy past from the application or something).

**Comment by richard-cox** [comment]
I think some of this functionality has changed since mid Dec '21.

The `application` [patch](https://github.com/epinio/epinio/blob/c9d36acc9f451c04b2e192e5e6e4c09cd8875755/docs/references/api/swagger.json#L247) request does contain an [ApplicationUpdateRequest](https://github.com/epinio/epinio/blob/c9d36acc9f451c04b2e192e5e6e4c09cd8875755/docs/references/api/swagger.json#L1184) object which contains a list of services. If updating service bindings this way isn't supported that object & docs need tweaking.

Generally though, I think we hit a similar issue with service's data. The UI would like to present a list that then replaces the current 'list' epinio backend side. @thardeck  Would that kind of thing be possible?

**Comment by thardeck** [comment]
You are right, ApplicationUpdateRequest does support changing the binding unlike the comment above the method. We have no tests for this though which I will add.

I was also able to delete the binding through this endpoint by providing an array with an empty string `'{ "services": [""] }'` but I suppose and empty array would be the more logical choice.

**Comment by thardeck** [comment]
I have added tests to the current working branch which prove that adding works but not deleting: https://github.com/epinio/epinio/tree/fix_application_update_api

There seem to be two issues.

First of our `ApplicationUpdateRequest` https://github.com/epinio/epinio/blob/main/pkg/api/core/v1/models/models.go#L142 does not allow Services to be nil, so it is not possible to delete bindings with an empty array in the PATCH request, because every request without a specified `services` field would provide an empty array and thus delete all service bindings if implemented correctly.

At the moment it only changes the services if the services array is not empty which does not allow deletion: https://github.com/epinio/epinio/blob/main/internal/api/v1/application/update.go#L113


The second issue is that if you provide an unknown service in a PATCH request like `{ "services": ["does_not_exist"] }` an error message is shown `{"errors":[{"status":404,"title":"Service 'does_not_exist' does not exist","details":""}]}` but still all  existing bindings are deleted.
I guess the best solution would be to change nothing if one request results in an error.

**Comment by andreas-kupries** [comment]
`ApplicationUpdateRequest` -- Currently an empty `Services` array is the indicator that `no changes to the services` are desired. A non-empty array is the set of new services to bind, __wholly replacing__ the old set ... This method can unbind services, just not the last/single service as I realize now. If you have `N > 1` services bound you can remove any `N-1` you want.

I remember that we did recently an API specifically for the UI, i.e. CLI and UI use different APIs, each tuned to what the respective client knows ... Ah, `ServiceUpdateRequest`, which is for editing a specific service. So, not for add/remove of services to apps.

So, a solution would be to change the `Services` field to a pointer to array/slice, and use `nil` as signal for `no changes`.
Then a non-nil, yet empty slice means `remove all` bindings.

Note that we have two explicit APIs to construct and delete individual bindings:

https://github.com/epinio/epinio/blob/d41d04e60a2e216ab240c274c6a50b6d2f1568c1/internal/api/v1/router.go#L97-L101

**Comment by richard-cox** [comment]
Reopening for validation

**Comment by juadk** [comment]
Successfully tested on 3.6.0
I was able to bind/unbind multiple times, I also checked that deployment was updated with or without the service.
I think we can add this test to Cypress, let me open an issue and update our confluence page for that.
